name: Build & Publish
on:
  push:
    branches:
      - main

jobs:
  release: 
    strategy:
        matrix:
          os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: yarn install
    - name: deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: yarn deploy