name: Build & Publish
on:
  push:
    branches:
      - main

jobs:
  release: 
    strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: install dependencies
      run: yarn install
    - name: deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
      run: yarn deploy